[workspace]
resolver = "2"

members = [
    "server-bin",
    "client-bin",
    "server",
    "client",
    "message",
    "network_manager",
    "realms",
    "tui",
    "user",
    "audio",
    "types"
]