[package]
name = "types"
version = "0.1.0"
edition = "2021"
description = "Common types used by the Kagu server and client."
license-file = "LICENSE.txt"
homepage = "https://github.com/bblsh/kagu"
repository = "https://github.com/bblsh/kagu"

[dependencies]
