[package]
name = "audio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
message = { path = "../message"}
types = { path = "../types" }

tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
cpal = "0.15.2"
bincode = { version = "1.3.3" }
serde = { version = "1.0.160", features = ["derive"] }
quinn = "*"
ringbuf = "0.3.3"