[package]
name = "server-bin"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/bin/server.rs"

[dependencies]
server = { path = "../server" }

clap = { version = "4.3.23", features = ["derive"] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }